version: "3.8"

services:
  db:
    image: postgres:15
    container_name: travel_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: travel_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: db
    restart: on-failure

volumes:
  postgres_data:
